near/near-workspaces-js

tests/status-message/__tests__/main.spec.ts

Remove `.test.near` suffixes from accounts created during test. Sandbox doesn't need this ¯\\\_(ツ)_/¯

fix: don't need test.near suffix

---

README.md

This includes information that is [potentially being removed from docs.near.org](https://github.com/near/docs/pull/805/files#diff-5e61f6fc99b1f0787beda827d607a9cf7157fce014d7367e81fda6d8f5e9f548L218)

docs: explain patchState, link to example

---

README.md

People new to JavaScript do not already know how to add a JavaScript testing library/framework to their project. This separates the "Quick Start" section of the README into two sections:
1. "Quick Start With Jest" explains that you don't _need_ to use Jest, but gets you up and running quickly with Jest for everyone who will find that helpful.
2. "How It Works" explains what near-runner does behind the scenes. The examples in this section use plain JS to help clarify the boundary between Jest and near-runner for people new to both.
Other updates that snuck in here:
* Use `path.join` instead of strings
* Update code styles to match current codebase (see https://github.com/near/runner-js/pull/38)
* Get rid of `runtime`, prefer `root` (see https://github.com/near/runner-js/pull/29)
* Remove …

docs: add Quick Start With Jest

---

README.md
package.json

And get rid of `pretest: yarn build` script, since tests now import directly from `src` instead of `dist`.

docs: fix & improve outdated README examples

---

jest.config.js
packages/jest/README.md
packages/jest/jest.config.js
yarn.lock

Jest's default `testMatch` will find ALL files in a `__tests__` directory.
Given the way we set up projects for people, this makes it hard to extract helper files. In https://github.com/near/near-sdk-rs/pull/569, I experienced this first-hand: I wanted to create a `utils.ts` file, and that required me to set up a whole `jest.config.js` and figure out how to extend the one from `near-runner-jest`.
With this change, people can just create utility files right in their `__tests__` directory. The only downside is for Jest power users who might expect to be able to omit the `spec` or `test` from their test filenames.

feat!(jest): add testMatch to default config

---

packages/jest/bootstrap-starter/near-runner/.gitignore

When people run their tests on testnet, near-runner will create a local .near-credentials directory. They should not commit this.

fix: add .near-credentials to bootstrap .gitignore

---

package.json

`yarn publish` is already a command, so this name doesn't work well with `scripts`
Since the `pre-` prefix means something else in package.json files, this also renames the `prerelease` script to `release:prerelease`.

build: rename 'publish' to 'release'

---

packages/js/dist/index.js
packages/js/dist/index.js.map
packages/js/jest.config.js
packages/js/package.json
packages/js/src/index.ts
yarn.lock

This depresses internal logs by default but you can add them back with NEAR_PRINT_LOGS.

chore: update naj and add NEAR_PRINT_LOGS

---

packages/jest/README.md

Update the README to mention that it is no longer the suggested way to use near-runner.

feat: deprecate near-runner-jest

---

packages/jest/package.json

This will allow us to remove `packages/jest` from this repository, but still have the code be findable from NPM, since it will link to a commit when the jest package still existed.

chore: point jest repository to specific commit

---

.gitignore
package.json
yarn.lock

`*.spec.ts` tests wouldn't run without this

chore: fix xo

---

packages/js/dist/container/server.js
packages/js/src/container/server.ts

Fixes: #125
Based on the testing, increase timeout setting to 60s would fix the issue. 
But a more comprehensive fix is to make the timeout configurable.

fix: sandbox start timeout

---

packages/js/README.md

@ailisp  npmjs.com requires README at the package level.
In order to avoid this duplication, we will need to move away from the multi-package repo.
I have created an issue for this: https://github.com/near/workspaces-js/issues/165

README added to js package

---

README.md
__tests__/02.patch-state.ava.ts
__tests__/03.single-use-access-keys-with-linkdrop.ava.ts
__tests__/04.cross-contract-calls-with-fungible-token.ava.ts
__tests__/05.spoon-contract-to-sandbox.ava.ts
__tests__/06.init-config.ava.ts
__tests__/07.resue-worker.ava.ts
examples/simple-project/__tests__/test-status-message.ava.js
packages/js/__tests__/record-builder.ava.ts

- Worker reuse example added
- The error string changed since we are not always in Sandbox mode.

Worker reuse example

---

.github/workflows/tests-sandbox.yml
packages/js/package.json
packages/js/src/server/server.ts
yarn.lock

- new `sandbox` requires new flags
- `macos` unit tests are turned off because of the issue with sandbox. Should be fixed in future versions.

Sandbox flags

---

__tests__/01.basic-transactions.ava.ts
__tests__/02.patch-state.ava.ts
__tests__/03.single-use-access-keys-with-linkdrop.ava.ts
__tests__/04.cross-contract-calls-with-fungible-token.ava.ts
__tests__/05.spoon-contract-to-sandbox.ava.ts
__tests__/06.init-config.ava.ts
__tests__/07.resue-worker.ava.ts
examples/simple-project/__tests__/test-status-message.ava.js
packages/js/__tests__/account.ava.ts
packages/js/__tests__/record-builder.ava.ts

Before this change, we were not stopping near-sandbox processes in case the test failed. With time it leads to high memory, CPU, and battery usage.
`afterEach.always(...)` solves the problem.

Kill all sandbox processes

---

packages/js/package.json
yarn.lock

The latest sandbox package should fix log spamming issues

chore/fix: Bump sandbox to latest, fixes log spamming

---

README.md

The "running on testnet" section's numbered list was formatted poorly. The cause is a one-space indentation error.

docs(readme): fix code block indentation

---

packages/js/package.json

The main breaking change is the maximum size of transactions which went from 4.2MB down to 1.5MB. It is safer to release it as 4.x series than risking breaking the users code. Overall, 4.0.0 release upgrade should be smooth for 3.x users.

release: v4.0.0 - bring nearcore 2.0.0 protocol breaking changes

---

README.md

fix: changed invalid links

---

__tests__/ci-ignore-02.patch-state.ava.ts
package.json
packages/js/package.json
packages/js/src/contract-state.ts
packages/js/src/utils.ts
pnpm-lock.yaml

BREAKING_CHANGE: 'borsh' update requires explicit 'Schema' parameter for serialization/deserialization.
https://github.com/near/near-workspaces-js/pull/246 I agreed with @r-near to continue his work, but I don’t have permissions to work on the repository branches.

chore: update 'borsh' and migrate to 'base58' libraries

---

.changeset/tangy-hotels-shine.md
.github/workflows/release.yml
package.json
packages/js/package.json
packages/js/src/internal-utils.ts
pnpm-lock.yaml

This PR documents recent changes and removes an interchangeable dependency to improve maintainability.

Documented Changes & Dependency Cleanup | Release 5.0.0
